### ISSUE TITLE
Bug Report: Week screen takes a dip in frames

### ISSUE THREAD

**Issue by DJDogster1384** [TheDrawingCoder-Gamer/Funkin#23] opened 2021-02-01 02:39 UTC
Hi. I know you've done a lot, but how come the Week screen takes 15 seconds to let me in, and then 3 or 5 seconds to let me scroll to the next week? Everything else is fine, and it's no biggie, but kind of is when you want to beat every single week on hard, and have to wait around 15 seconds a pop

**Comment by TheDrawingCoder-Gamer** [comment] 2021-02-01 14:05
Duplicate of #18

**Comment by TheDrawingCoder-Gamer** [comment] 2021-02-01 14:24
The reason this takes forever is because it has to load _all_ of custom images for the characters. I took this as a tradeoff to prevent a laggy week menu

**Comment by TheDrawingCoder-Gamer** [comment] 2021-02-01 15:01
People seem to really hate this new update. I am going to do traditional optimizations to make load time reasonable.

**Comment by TheDrawingCoder-Gamer** [comment] 2021-02-01 15:26
The commit fe9aa3f5efed9b797b2dce4cfb5b4a50a1f80aeb solves this, and will be in the next update.

**Closed by TheDrawingCoder-Gamer** 2021-02-01 15:26 UTC
Labels: bug
